version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

# INSTALL DOCKER DESKTOP
# CHECK IF PORT 3306 IS FREE: Get-Process -Id (Get-NetTCPConnection -LocalPort 3306).OwningProcess
# FREE UP PORT 3306: Stop-Process -Id 12345 -Force
# RUN DB: $ docker-compose -f db.yaml up -d
# CONNECT TO MYSQL DB USING MYSQL WORKBENCH

